CREATE OR ALTER PROCEDURE SCH_CENTRA_ID.SELECT_REPROCESO_BY_ESTADO @P0 nvarchar(1)
AS
BEGIN
	DECLARE @TEMP_REPROCESO_IDS TABLE (
		REPROC_GUID varchar (50) NOT NULL
	)
	BEGIN TRANSACTION

	SET NOCOUNT ON
	INSERT INTO @TEMP_REPROCESO_IDS SELECT GUID FROM MGI_REPROCESO 
	WHERE ESTADO=@P0 AND IS_RETRY_INPROGRESS=0 ORDER BY PRIORIDAD ASC

	SET NOCOUNT ON
	UPDATE MGI_REPROCESO SET IS_RETRY_INPROGRESS = 1, ROW_VERSION=ROW_VERSION+1 WHERE GUID IN (SELECT REPROC_GUID FROM @TEMP_REPROCESO_IDS)

	SET NOCOUNT OFF
	SELECT GUID,FECHA_INGRESO,ID_MENSAJE,ESTADO,USER_STORE,MENSAJE_PETICION,MENSAJE_RESPUESTA,PRIORIDAD,REINTENTO,SOAP_ACTION,STATUS_COD_RESP,ULTIMA_FECHA_REINTENTO,HP_TICKET_NUMERO,
	HP_TICKET_CONTENIDO,HP_TICKET_FECHA_RESPUESTA,HP_TICKET_ESTADO, HP_TICKET_LOGS,UUID_GI, ROW_VERSION 
	FROM MGI_REPROCESO 
	WHERE GUID IN (SELECT REPROC_GUID FROM @TEMP_REPROCESO_IDS) ORDER BY PRIORIDAD ASC
	
	COMMIT TRANSACTION  
	RETURN
END