USE [CENTRA_ID]
GO

UPDATE "SCH_CENTRA_ID"."APPLICATIONS_GROUP" SET "CODE" = 'LOGICIEL', "NAME" = 'LOGICIEL' WHERE "CODE" = 'LOGIFLOW'
GO

ALTER TABLE "CENTRA_ID"."SCH_CENTRA_ID"."USERDATA" ALTER COLUMN "EMPLOYEE_STATUS" nvarchar(50)  NOT NULL
GO
